### ISSUE TITLE
Resolving `ember-modifier` deprecation warnings

### ISSUE THREAD

**Issue by Poltergeistz** [lblod/frontend-loket#139]
This is a patch to deprecation warnings triggered by `ember-style-modifier` & `ember-inputmask5` on route `/mandatenbeheer/mandatarissen/new-person`

Overriding ember-style-modifier to version ![0.8.0](https://github.com/jelhan/ember-style-modifier/blob/master/CHANGELOG.md) solves the deprecation warning in the app related to this dependency. 

I believe Appuniversum is using ember-inputmask5, this is also triggering warnings on loket : 
- The `didInstall`, `didReceiveArguments`, and `didUpdateArguments` hooks are deprecated. Use the new `modify` hook instead.
- Using `this.args` is deprecated. Access positional and named arguments directly in the `modify` hook instead.
- Using `this.element` is deprecated. Access the `element` as an argument in the `modify` hook instead

Bumping `ember-inputmask5` to version ![4.0.1](https://github.com/sinankeskin/ember-inputmask/blob/main/CHANGELOG.md) solves the warnings. I did override this dependency too for now.

Related to Appuniversum issue ![#223](https://github.com/appuniversum/ember-appuniversum/issues/223)

Ready for PR.

**Comment by Windvis** [comment]
I think the remaining deprecations have been resolved with the Appuniversum v2 update 👍.
